plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.21'
}

group = 'cn.edu.shmtu.cas'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jsoup:jsoup:1.22.2'
    implementation("com.squareup.okhttp3:okhttp:5.3.2")
}

kotlin {
    jvmToolchain(21)
}
