plugins {
    id 'com.android.library' version '9.2.1' apply false
    id 'org.jetbrains.kotlin.jvm' version '2.2.10' apply false
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.2.10' apply false
}

subprojects {
    group = System.getenv("GROUP") ?: 'cn.edu.shmtu.cas'
    version = System.getenv("VERSION") ?: '1.0-SNAPSHOT'

    repositories {
        google()
        mavenCentral()
    }
}
