plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'java-library'
    id 'maven-publish'
}

java {
    withSourcesJar()
}

dependencies {
    implementation 'org.jsoup:jsoup:1.22.2'
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0'
}

kotlin {
    jvmToolchain(17)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group
            artifactId = 'shmtu-cas-jvm'
            version = project.version

            pom {
                name = 'SHMTU CAS JVM Library'
                description = 'JVM library for SHMTU CAS login and bill querying.'
            }
        }
    }
}
